name: Node GOAT CI Pipeline - Part 2 (Parallel Scans with Self-Hosted Runner)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  # Job for building and pushing the Docker image
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/itas276-nodegoat:latest
          # Make sure image is set as private in DockerHub after pushing

  # SAST scanning using Semgrep on GitHub runner
  sast-scan:
    runs-on: ubuntu-latest
    # Remove the 'needs' to run in parallel, not sequentially
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Semgrep scan
        uses: semgrep/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"
          config: >-
            p/security-audit
            p/javascript

      - name: Upload SARIF file for SAST
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
          category: semgrep

  # SCA scanning using GitHub built-in Dependency Scanning on Self-Hosted Runner
  # Replace 'itas276-yourusername' with your actual runner label
  sca-scan:
    runs-on: itas276-yourusername
    # Remove the 'needs' to run in parallel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Use npm audit for SCA
      - name: Run npm audit for SCA
        run: |
          npm audit --json > npm-audit.json || true
          
      - name: Convert npm audit to SARIF
        run: |
          echo '{
            "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
            "version": "2.1.0",
            "runs": [
              {
                "tool": {
                  "driver": {
                    "name": "npm audit",
                    "informationUri": "https://docs.npmjs.com/cli/audit",
                    "rules": []
                  }
                },
                "results": []
              }
            ]
          }' > npm-audit.sarif
          
      - name: Upload npm audit results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: npm-audit.sarif
          category: npm-audit

  # Compare the run time between the two scans
  compare-run-time:
    runs-on: ubuntu-latest
    needs: [sast-scan, sca-scan]
    steps:
      - name: Show completion
        run: echo "Both SAST and SCA scans completed. Check the run time in the GitHub Actions UI."