name: Node GOAT CI Pipeline - Part 2 (Parallel Scans)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      run: |
        docker login -u "yorkzap" -p "dckr_pat_dUjRsWRQWsZsc_Dlmxf7Zep1SD0"
        
    - name: Build the Docker Image
      run: |
        docker build -t yorkzap/itas-git-nodegoat-rajsingh:latest .
        
    - name: Push Docker Image to Docker Hub
      run: |
        docker push yorkzap/itas-git-nodegoat-rajsingh:latest

  # SAST scanning using Semgrep on GitHub runner (in parallel)
  semgrep-sast:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    # No "needs" dependency to run in parallel
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep scan
        run: |
          # Install semgrep
          pip install semgrep
          # Run the scan
          semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ae59248ceb08a5ea55ac0e0e8aa5693b81cc931d0fb40c92621a14140ae3566d
            
      - name: Upload Semgrep SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep.sarif

  # SCA scanning using NPM Audit on Self-Hosted Runner
  npm-audit-sca:
    name: NPM Audit SCA Scan
    # Replace this with your actual self-hosted runner label
    runs-on: self-hosted
    # No "needs" dependency to run in parallel
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run npm audit
        run: npm audit --json > npm-audit.json || true
        
      - name: Upload npm audit results
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-results
          path: npm-audit.json
          
  # Compare run times
  compare-times:
    runs-on: ubuntu-latest
    needs: [semgrep-sast, npm-audit-sca]
    steps:
      - name: Completion message
        run: echo "Both SAST and SCA scans completed. Check the run times in the Actions tab."